spring:
  cache:
    type: simple
  h2:
    console:
      enabled: true  # Habilita la consola web de H2
      path: /h2-console  # Ruta para acceder a la consola H2
  datasource:
    url: jdbc:h2:mem:testdb # Base de datos en memoria
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: create  # Crea la base de datos al iniciar la aplicación
    show-sql: true  # Muestra las consultas SQL en la consola
server:
  port: 9191  # Puerto en el que correrá la aplicación
